CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE NB (
    ID INT,
    NAME VARCHAR(255)
);

CREATE TABLE HOGE (
    ID INT,
    UUID UUID NOT NULL DEFAULT uuid_generate_v4(),
    NAME VARCHAR(255),
    STATE VARCHAR(10)
);